### PR TITLE
Initial Setup

### PR DESCRIPTION
**Pull request by jlberbesi**
## Setup: "Hello Microverse project"

In this  milestone I:

- Created a new GitHub repo
- Created a new branch according to the [GitHub flow]
- Set up a linter for HTML and CSS
- Added descriptive README file.
- Added 3 files (html, css, test.md):

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @jlberbesi, 

# Status: Changes Required ♻️

First, I welcome you to Microverse.

You have done good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

Almost there

## Good Highlights✔

- Good commit messages

## Required Changes ♻️

- Kindly set up the correct linters for this project following the [linters documentation](https://github.com/microverseinc/linters-config/tree/master/html-css) for HTML/CSS projects and ensure to ignore the `node_modules` folder in the process.

- Kindly ensure that you provide a descriptive summary to your PR describing the changes inside
- I can see that you have merged some changes (which are supposed to be part of this milestone) to your master branch. Please, always ensure that all changes expected of a milestone are contained on the same feature branch. This is to help to make all changes made on the project reviewable hence following the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). Kindly ensure this is followed in subsequent projects at Microverse.
- You have done great by using the README template provided. Please, ensure that you customize your README template to match the current project it is used in.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jlberbesi** [comment]
@emmiiorji 

Thanks a lot for your recommendations.

I'd like to let you know I already summited those changes suggested by you. 

Looking forward to hearing back from you.

**Comment by emmiiorji** [comment]
> @emmiiorji
> 
> Thanks a lot for your recommendations.
> 
> I'd like to let you know I already summited those changes suggested by you.
> 
> Looking forward to hearing back from you.

Hi @jlberbesi,

Great job. Kindly resubmit the project on your dashboard for another review.

Thank you.

**Review by emmiiorji — APPROVED** [review]
Hi @jlberbesi, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and I wish you a pleasant learning experience at Microverse! 🎉 

congratulations


## Good Highlights✔

- Linter checks are passing
- Good commit messages
- You have implemented requested changes


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
